// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCustomer = "customers"

// Customer mapped from table <customers>
type Customer struct {
	CustomerID   int64     `gorm:"column:customer_id;primaryKey;autoIncrement:true" json:"customer_id"`
	Nik          string    `gorm:"column:nik;not null" json:"nik"`
	NamaLengkap  string    `gorm:"column:nama_lengkap;not null" json:"nama_lengkap"`
	TanggalLahir time.Time `gorm:"column:tanggal_lahir" json:"tanggal_lahir"`
	NoHp         string    `gorm:"column:no_hp;not null" json:"no_hp"`
	Email        string    `gorm:"column:email" json:"email"`
	Pekerjaan    string    `gorm:"column:pekerjaan" json:"pekerjaan"`
	Perusahaan   string    `gorm:"column:perusahaan" json:"perusahaan"`
	Salary       float64   `gorm:"column:salary" json:"salary"`
	LocationID   int64     `gorm:"column:location_id" json:"location_id"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
