// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameKabupaten = "kabupaten"

// Kabupaten mapped from table <kabupaten>
type Kabupaten struct {
	KabID   int64  `gorm:"column:kab_id;primaryKey;autoIncrement:true" json:"kab_id"`
	KabName string `gorm:"column:kab_name;not null" json:"kab_name"`
	ProvID  int64  `gorm:"column:prov_id;not null" json:"prov_id"`
}

// TableName Kabupaten's table name
func (*Kabupaten) TableName() string {
	return TableNameKabupaten
}
