// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameKecamatan = "kecamatan"

// Kecamatan mapped from table <kecamatan>
type Kecamatan struct {
	KecID   int64  `gorm:"column:kec_id;primaryKey;autoIncrement:true" json:"kec_id"`
	KecName string `gorm:"column:kec_name;not null" json:"kec_name"`
	KabID   int64  `gorm:"column:kab_id;not null" json:"kab_id"`
}

// TableName Kecamatan's table name
func (*Kecamatan) TableName() string {
	return TableNameKecamatan
}
