// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeasingContract = "leasing_contract"

// LeasingContract mapped from table <leasing_contract>
type LeasingContract struct {
	ContractID        int64     `gorm:"column:contract_id;primaryKey;autoIncrement:true" json:"contract_id"`
	ContractNumber    string    `gorm:"column:contract_number" json:"contract_number"`
	RequestDate       time.Time `gorm:"column:request_date;not null;default:CURRENT_DATE" json:"request_date"`
	TanggalAkad       time.Time `gorm:"column:tanggal_akad" json:"tanggal_akad"`
	TanggalMulaiCicil time.Time `gorm:"column:tanggal_mulai_cicil" json:"tanggal_mulai_cicil"`
	TenorBulan        int16     `gorm:"column:tenor_bulan;not null" json:"tenor_bulan"`
	NilaiKendaraan    float64   `gorm:"column:nilai_kendaraan;not null" json:"nilai_kendaraan"`
	DpDibayar         float64   `gorm:"column:dp_dibayar;not null" json:"dp_dibayar"`
	PokokPinjaman     float64   `gorm:"column:pokok_pinjaman;not null" json:"pokok_pinjaman"`
	TotalPinjaman     float64   `gorm:"column:total_pinjaman;not null" json:"total_pinjaman"`
	CicilanPerBulan   float64   `gorm:"column:cicilan_per_bulan;not null" json:"cicilan_per_bulan"`
	Status            string    `gorm:"column:status;not null;default:draft" json:"status"`
	CreatedAt         time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CustomerID        int64     `gorm:"column:customer_id;not null" json:"customer_id"`
	MotorID           int64     `gorm:"column:motor_id;not null" json:"motor_id"`
	ProductID         int64     `gorm:"column:product_id;not null" json:"product_id"`
}

// TableName LeasingContract's table name
func (*LeasingContract) TableName() string {
	return TableNameLeasingContract
}
