// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeasingContractDocument = "leasing_contract_documents"

// LeasingContractDocument mapped from table <leasing_contract_documents>
type LeasingContractDocument struct {
	LdocID     int64     `gorm:"column:ldoc_id;primaryKey;autoIncrement:true" json:"ldoc_id"`
	FileName   string    `gorm:"column:file_name;not null" json:"file_name"`
	FileSize   float64   `gorm:"column:file_size" json:"file_size"`
	FileType   string    `gorm:"column:file_type" json:"file_type"`
	FileURL    string    `gorm:"column:file_url;not null" json:"file_url"`
	ContractID int64     `gorm:"column:contract_id;not null" json:"contract_id"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName LeasingContractDocument's table name
func (*LeasingContractDocument) TableName() string {
	return TableNameLeasingContractDocument
}
