// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeasingProduct = "leasing_product"

// LeasingProduct mapped from table <leasing_product>
type LeasingProduct struct {
	ProductID   int64     `gorm:"column:product_id;primaryKey;autoIncrement:true" json:"product_id"`
	KodeProduk  string    `gorm:"column:kode_produk;not null" json:"kode_produk"`
	NamaProduk  string    `gorm:"column:nama_produk;not null" json:"nama_produk"`
	TenorBulan  int16     `gorm:"column:tenor_bulan;not null" json:"tenor_bulan"`
	DpPersenMin float64   `gorm:"column:dp_persen_min;not null" json:"dp_persen_min"`
	DpPersenMax float64   `gorm:"column:dp_persen_max;not null" json:"dp_persen_max"`
	BungaFlat   float64   `gorm:"column:bunga_flat;not null" json:"bunga_flat"`
	AdminFee    float64   `gorm:"column:admin_fee" json:"admin_fee"`
	Asuransi    bool      `gorm:"column:asuransi;default:true" json:"asuransi"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName LeasingProduct's table name
func (*LeasingProduct) TableName() string {
	return TableNameLeasingProduct
}
