// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeasingTask = "leasing_tasks"

// LeasingTask mapped from table <leasing_tasks>
type LeasingTask struct {
	TaskID          int64     `gorm:"column:task_id;primaryKey;autoIncrement:true" json:"task_id"`
	TaskName        string    `gorm:"column:task_name;not null" json:"task_name"`
	Startdate       time.Time `gorm:"column:startdate" json:"startdate"`
	Enddate         time.Time `gorm:"column:enddate" json:"enddate"`
	ActualStartdate time.Time `gorm:"column:actual_startdate" json:"actual_startdate"`
	ActualEnddate   time.Time `gorm:"column:actual_enddate" json:"actual_enddate"`
	Status          string    `gorm:"column:status;default:inprogress" json:"status"`
	ContractID      int64     `gorm:"column:contract_id;not null" json:"contract_id"`
	RoleID          int64     `gorm:"column:role_id;not null" json:"role_id"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	SequenceNo      int16     `gorm:"column:sequence_no" json:"sequence_no"`
	CallFunction    string    `gorm:"column:call_function" json:"call_function"`
}

// TableName LeasingTask's table name
func (*LeasingTask) TableName() string {
	return TableNameLeasingTask
}
