// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameLeasingTasksAttribute = "leasing_tasks_attributes"

// LeasingTasksAttribute mapped from table <leasing_tasks_attributes>
type LeasingTasksAttribute struct {
	TasaID     int64     `gorm:"column:tasa_id;primaryKey;autoIncrement:true" json:"tasa_id"`
	TasaName   string    `gorm:"column:tasa_name;not null" json:"tasa_name"`
	TasaValue  string    `gorm:"column:tasa_value" json:"tasa_value"`
	TasaStatus string    `gorm:"column:tasa_status;default:inprogress" json:"tasa_status"`
	TasaTaskID int64     `gorm:"column:tasa_task_id;not null" json:"tasa_task_id"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName LeasingTasksAttribute's table name
func (*LeasingTasksAttribute) TableName() string {
	return TableNameLeasingTasksAttribute
}
