// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	LocationID    int64   `gorm:"column:location_id;primaryKey;autoIncrement:true" json:"location_id"`
	StreetAddress string  `gorm:"column:street_address" json:"street_address"`
	PostalCode    string  `gorm:"column:postal_code" json:"postal_code"`
	Longitude     float64 `gorm:"column:longitude" json:"longitude"`
	Latitude      float64 `gorm:"column:latitude" json:"latitude"`
	KelID         int64   `gorm:"column:kel_id" json:"kel_id"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
