// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMotorAsset = "motor_assets"

// MotorAsset mapped from table <motor_assets>
type MotorAsset struct {
	MoasID      int64     `gorm:"column:moas_id;primaryKey;autoIncrement:true" json:"moas_id"`
	FileName    string    `gorm:"column:file_name;not null" json:"file_name"`
	FileSize    float64   `gorm:"column:file_size" json:"file_size"`
	FileType    string    `gorm:"column:file_type" json:"file_type"`
	FileURL     string    `gorm:"column:file_url;not null" json:"file_url"`
	MoasMotorID int64     `gorm:"column:moas_motor_id;not null" json:"moas_motor_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName MotorAsset's table name
func (*MotorAsset) TableName() string {
	return TableNameMotorAsset
}
