// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameMotor = "motors"

// Motor mapped from table <motors>
type Motor struct {
	MotorID     int64     `gorm:"column:motor_id;primaryKey;autoIncrement:true" json:"motor_id"`
	Merk        string    `gorm:"column:merk;not null;default:Honda" json:"merk"`
	MotorType   string    `gorm:"column:motor_type" json:"motor_type"`
	Tahun       int16     `gorm:"column:tahun;not null" json:"tahun"`
	Warna       string    `gorm:"column:warna" json:"warna"`
	NomorRangka string    `gorm:"column:nomor_rangka;not null" json:"nomor_rangka"`
	NomorMesin  string    `gorm:"column:nomor_mesin;not null" json:"nomor_mesin"`
	CcMesin     string    `gorm:"column:cc_mesin" json:"cc_mesin"`
	NomorPolisi string    `gorm:"column:nomor_polisi" json:"nomor_polisi"`
	StatusUnit  string    `gorm:"column:status_unit;default:ready" json:"status_unit"`
	HargaOtr    float64   `gorm:"column:harga_otr;not null" json:"harga_otr"`
	MotorMotyID int64     `gorm:"column:motor_moty_id;not null" json:"motor_moty_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Motor's table name
func (*Motor) TableName() string {
	return TableNameMotor
}
