// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	PaymentID        int64     `gorm:"column:payment_id;primaryKey;autoIncrement:true" json:"payment_id"`
	NomorBukti       string    `gorm:"column:nomor_bukti;not null" json:"nomor_bukti"`
	JumlahBayar      float64   `gorm:"column:jumlah_bayar;not null" json:"jumlah_bayar"`
	TanggalBayar     time.Time `gorm:"column:tanggal_bayar;not null" json:"tanggal_bayar"`
	MetodePembayaran string    `gorm:"column:metode_pembayaran;not null" json:"metode_pembayaran"`
	Provider         string    `gorm:"column:provider" json:"provider"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	ContractID       int64     `gorm:"column:contract_id;not null" json:"contract_id"`
	ScheduleID       int64     `gorm:"column:schedule_id" json:"schedule_id"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
