// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePaymentSchedule = "payment_schedule"

// PaymentSchedule mapped from table <payment_schedule>
type PaymentSchedule struct {
	ScheduleID       int64     `gorm:"column:schedule_id;primaryKey;autoIncrement:true" json:"schedule_id"`
	AngsuranKe       int16     `gorm:"column:angsuran_ke;not null" json:"angsuran_ke"`
	JatuhTempo       time.Time `gorm:"column:jatuh_tempo;not null" json:"jatuh_tempo"`
	Pokok            float64   `gorm:"column:pokok;not null" json:"pokok"`
	Margin           float64   `gorm:"column:margin;not null" json:"margin"`
	TotalTagihan     float64   `gorm:"column:total_tagihan;not null" json:"total_tagihan"`
	StatusPembayaran string    `gorm:"column:status_pembayaran;default:unpaid" json:"status_pembayaran"`
	TanggalBayar     time.Time `gorm:"column:tanggal_bayar" json:"tanggal_bayar"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	ContractID       int64     `gorm:"column:contract_id;not null" json:"contract_id"`
}

// TableName PaymentSchedule's table name
func (*PaymentSchedule) TableName() string {
	return TableNamePaymentSchedule
}
