// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProvince = "province"

// Province mapped from table <province>
type Province struct {
	ProvID   int64  `gorm:"column:prov_id;primaryKey;autoIncrement:true" json:"prov_id"`
	ProvName string `gorm:"column:prov_name;not null" json:"prov_name"`
}

// TableName Province's table name
func (*Province) TableName() string {
	return TableNameProvince
}
