// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameRolePermission = "role_permission"

// RolePermission mapped from table <role_permission>
type RolePermission struct {
	RolePermissionID int64 `gorm:"column:role_permission_id;primaryKey;autoIncrement:true" json:"role_permission_id"`
	RoleID           int64 `gorm:"column:role_id;not null" json:"role_id"`
	PermissionID     int64 `gorm:"column:permission_id;not null" json:"permission_id"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
