// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTemplateTask = "template_tasks"

// TemplateTask mapped from table <template_tasks>
type TemplateTask struct {
	TetaID       int64     `gorm:"column:teta_id;primaryKey;autoIncrement:true" json:"teta_id"`
	TetaName     string    `gorm:"column:teta_name;not null" json:"teta_name"`
	TetaRoleID   int64     `gorm:"column:teta_role_id;not null" json:"teta_role_id"`
	Description  string    `gorm:"column:description" json:"description"`
	SequenceNo   int16     `gorm:"column:sequence_no" json:"sequence_no"`
	IsRequired   bool      `gorm:"column:is_required;default:true" json:"is_required"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CallFunction string    `gorm:"column:call_function" json:"call_function"`
}

// TableName TemplateTask's table name
func (*TemplateTask) TableName() string {
	return TableNameTemplateTask
}
