// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameTemplateTaskAttribute = "template_task_attributes"

// TemplateTaskAttribute mapped from table <template_task_attributes>
type TemplateTaskAttribute struct {
	TetatID       int64     `gorm:"column:tetat_id;primaryKey;autoIncrement:true" json:"tetat_id"`
	TetatName     string    `gorm:"column:tetat_name;not null" json:"tetat_name"`
	TetatTetaID   int64     `gorm:"column:tetat_teta_id;not null" json:"tetat_teta_id"`
	Description   string    `gorm:"column:description" json:"description"`
	IsRequired    bool      `gorm:"column:is_required;default:true" json:"is_required"`
	AttributeType string    `gorm:"column:attribute_type" json:"attribute_type"`
	CreatedAt     time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName TemplateTaskAttribute's table name
func (*TemplateTaskAttribute) TableName() string {
	return TableNameTemplateTaskAttribute
}
