// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID         int64     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username       string    `gorm:"column:username" json:"username"`
	PhoneNumber    string    `gorm:"column:phone_number;not null" json:"phone_number"`
	Email          string    `gorm:"column:email" json:"email"`
	FullName       string    `gorm:"column:full_name;not null" json:"full_name"`
	Password       string    `gorm:"column:password" json:"password"`
	PinKey         string    `gorm:"column:pin_key" json:"pin_key"`
	IsActive       bool      `gorm:"column:is_active;default:true" json:"is_active"`
	LastLogin      time.Time `gorm:"column:last_login" json:"last_login"`
	FailedAttempts int16     `gorm:"column:failed_attempts" json:"failed_attempts"`
	LockedUntil    time.Time `gorm:"column:locked_until" json:"locked_until"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
