// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	UserRoleID int64     `gorm:"column:user_role_id;primaryKey;autoIncrement:true" json:"user_role_id"`
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`
	RoleID     int64     `gorm:"column:role_id;not null" json:"role_id"`
	AssignedAt time.Time `gorm:"column:assigned_at;default:CURRENT_TIMESTAMP" json:"assigned_at"`
	AssignedBy int64     `gorm:"column:assigned_by" json:"assigned_by"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
