// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserOauthProvider = "user_oauth_provider"

// UserOauthProvider mapped from table <user_oauth_provider>
type UserOauthProvider struct {
	UserOauthID  int64     `gorm:"column:user_oauth_id;primaryKey;autoIncrement:true" json:"user_oauth_id"`
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`
	ProviderID   int64     `gorm:"column:provider_id;not null" json:"provider_id"`
	AccessToken  string    `gorm:"column:access_token" json:"access_token"`
	RefreshToken string    `gorm:"column:refresh_token" json:"refresh_token"`
	ExpiresAt    time.Time `gorm:"column:expires_at" json:"expires_at"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName UserOauthProvider's table name
func (*UserOauthProvider) TableName() string {
	return TableNameUserOauthProvider
}
