// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package leasing

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                       = new(Query)
	LeasingContract         *leasingContract
	LeasingContractDocument *leasingContractDocument
	LeasingProduct          *leasingProduct
	LeasingTask             *leasingTask
	LeasingTasksAttribute   *leasingTasksAttribute
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	LeasingContract = &Q.LeasingContract
	LeasingContractDocument = &Q.LeasingContractDocument
	LeasingProduct = &Q.LeasingProduct
	LeasingTask = &Q.LeasingTask
	LeasingTasksAttribute = &Q.LeasingTasksAttribute
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		LeasingContract:         newLeasingContract(db, opts...),
		LeasingContractDocument: newLeasingContractDocument(db, opts...),
		LeasingProduct:          newLeasingProduct(db, opts...),
		LeasingTask:             newLeasingTask(db, opts...),
		LeasingTasksAttribute:   newLeasingTasksAttribute(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	LeasingContract         leasingContract
	LeasingContractDocument leasingContractDocument
	LeasingProduct          leasingProduct
	LeasingTask             leasingTask
	LeasingTasksAttribute   leasingTasksAttribute
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		LeasingContract:         q.LeasingContract.clone(db),
		LeasingContractDocument: q.LeasingContractDocument.clone(db),
		LeasingProduct:          q.LeasingProduct.clone(db),
		LeasingTask:             q.LeasingTask.clone(db),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		LeasingContract:         q.LeasingContract.replaceDB(db),
		LeasingContractDocument: q.LeasingContractDocument.replaceDB(db),
		LeasingProduct:          q.LeasingProduct.replaceDB(db),
		LeasingTask:             q.LeasingTask.replaceDB(db),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.replaceDB(db),
	}
}

type queryCtx struct {
	LeasingContract         ILeasingContractDo
	LeasingContractDocument ILeasingContractDocumentDo
	LeasingProduct          ILeasingProductDo
	LeasingTask             ILeasingTaskDo
	LeasingTasksAttribute   ILeasingTasksAttributeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		LeasingContract:         q.LeasingContract.WithContext(ctx),
		LeasingContractDocument: q.LeasingContractDocument.WithContext(ctx),
		LeasingProduct:          q.LeasingProduct.WithContext(ctx),
		LeasingTask:             q.LeasingTask.WithContext(ctx),
		LeasingTasksAttribute:   q.LeasingTasksAttribute.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
